### ISSUE TITLE
Build failure (commit d63c2fd)

### ISSUE THREAD

**Issue by bland328** [kdschlosser/lvgl_micropython#32]
After a fresh clone of the repo under macOS and running:

`python3 make.py esp32 submodules clean mpy_cross BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEX=gt911`

I eventually get this error...

```
Including User C Module(s) from ../../../../../micropython.cmake
Traceback (most recent call last):
File "/Users/brian/code/esp-idf/lvgl_micropython/gen/python_api_gen_mpy.py", line 272, in <module>
cpp_cmd.append(f'"{input_headers[0]}"')
~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

...which appears to me perhaps because `micropython.cmake` is missing the `--header_file=` option text near the end of this line:

```
${Python3_EXECUTABLE} ${CMAKE_CURRENT_LIST_DIR}/gen/$ENV{GEN_SCRIPT}_api_gen_mpy.py ${LV_CFLAGS} --output=${CMAKE_BINARY_DIR}/lv_mp.c --include=${CMAKE_CURRENT_LIST_DIR} --include=${CMAKE_CURRENT_LIST_DIR}/include --include=${CMAKE_CURRENT_LIST_DIR}/lvgl --board=$ENV{LV_PORT} --module_name=lvgl --module_prefix=lv --metadata=${CMAKE_BINARY_DIR}/lv_mp.c.json ${LVGL_HEADER}
```

If I do change that final argument to `--header_file=${LVGL_HEADER}`, the build gets farther, but then eventually fails with:

```
Including User C Module(s) from ../../../../../micropython.cmake
Traceback (most recent call last):
File "/Users/brian/code/esp-idf/lvgl_micropython/gen/python_api_gen_mpy.py", line 3649, in <module>
obj_metadata[obj_name]['methods'].update(deepcopy(obj_metadata[obj_name]['members']))
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'members'
```

**Comment by kdschlosser** [comment]
I am checking on this now. I made a LOT OF Changes to get SDL2 to work properly on the unix port so I could have boogered something up in the generation script that is causing this problem.
