### ISSUE TITLE
RPEL not working in a ESP32-S2 custom board

### ISSUE THREAD

**Issue by Alby1987** [kdschlosser/lvgl_micropython#49]
I'm trying to make a Lvgl for MicroPython using your software. Using a precompiled Micropython for my Esp32_generic_s2 works, but when building the firmware with lvgl with your I get a non working RPEL and Pykmr says it can not connect. This is my command

make.py esp32 submodules clean mpy_cross BOARD=ESP32_GENERIC_S2 DISPLAY=ili9488 INDEV=gt911
then program it via ttyUSB0. ttyUSB0 is a USB-to-UART converter to TXD and RXD pins.

When using the official build, I get the possibility to work on the REPL via ttyACM0, usb connected to IO19 and IO20, this is not available with the built lvgl firmware (device is not recognized by the OS?)

**Comment by kdschlosser** [comment]
I added a new build command to enable the serial output over the USB OTG (JTAG) pins.

Add `--USB-OTG` to the end of your build command. That will fix your problem.

**Comment by kdschlosser** [comment]
You need to clone the repo again as I just added that feature like 2 minutes ago.

**Comment by Alby1987** [comment]
I've just tried it, it works! Thanks! Now fighting against initializing my ILI9488, but that should be just a matter of testings...

**Comment by kdschlosser** [comment]
The bus drivers look pretty good. I believe the only one that has not been tested is the I2C driver at this point. Some of the display IC drivers have been tested. I believe the ILI9488 has already been tested and it was considered to be working. If you have something going on with it that's not working properly let me know and I will straighten it out.

**Comment by fabse-hack** [comment]
@kdschlosser with the LOLIN_S2_MINI is the same problem. 

- With the ESP32_S2_GENERIC and --usb-otg is possible to open the REPL ....
- LOLIN_S2_MINI not have the option --usb-otg and is not possible to open REPL ...

btw is `--usb-otg` .... not `--USB-OTG` (i think there is general problem in the command line with lower() and upper()
