### ISSUE TITLE
Compile problem using ESP-IDF 5.2.1 and MicroPython 1.23.0 

### ISSUE THREAD

**Issue by kdschlosser** [kdschlosser/lvgl_micropython#54]
There is a compile issue with nimble and I have opened an issue with MicroPython for the problem. Hopefully they will fix it pretty quickly and get a release made for it. Otherwise I am going to have to patch the code. Not something I really want to do.

https://github.com/micropython/micropython/issues/15287

**Comment by zelogik** [comment]
So maybe my new error at compile time is related...

<details error>
  <summary>Error linking</summary>
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/esp-idf/components/esp_coex/lib/esp32/libcoexist.a(coexist_hw.o):(.iram1.17+0x0): undefined reference to `btdm_rf_bb_reg_init'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/esp-idf/components/esp_coex/lib/esp32/libcoexist.a(coexist_hw.o):(.iram1.17+0x16): undefined reference to `btdm_rf_bb_reg_init'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gattc_exchange_mtu+0x0): undefined reference to `mp_bluetooth_gattc_exchange_mtu'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gattc_write+0x0): undefined reference to `mp_bluetooth_gattc_write'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gattc_read+0x0): undefined reference to `mp_bluetooth_gattc_read'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gattc_discover_descriptors+0x0): undefined reference to `mp_bluetooth_gattc_discover_descriptors'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gattc_discover_characteristics+0x4): undefined reference to `mp_bluetooth_gattc_discover_characteristics'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gattc_discover_services+0x0): undefined reference to `mp_bluetooth_gattc_discover_primary_services'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gatts_set_buffer+0x0): undefined reference to `mp_bluetooth_gatts_set_buffer'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gatts_notify_indicate+0x0): undefined reference to `mp_bluetooth_gatts_notify_indicate'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gatts_write+0x0): undefined reference to `mp_bluetooth_gatts_write'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gatts_read+0x0): undefined reference to `mp_bluetooth_gatts_read'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gatts_register_services+0x10): undefined reference to `mp_bluetooth_gatts_register_service_begin'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gatts_register_services+0x14): undefined reference to `mp_bluetooth_gatts_register_service'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gatts_register_services+0x18): undefined reference to `mp_bluetooth_gatts_register_service_end'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_passkey+0x0): undefined reference to `mp_bluetooth_gap_passkey'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_pair+0x0): undefined reference to `mp_bluetooth_gap_pair'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_disconnect+0x0): undefined reference to `mp_bluetooth_gap_disconnect'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_scan+0x8): undefined reference to `mp_bluetooth_gap_scan_stop'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_scan+0xc): undefined reference to `mp_bluetooth_gap_scan_start'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_advertise+0x4): undefined reference to `mp_bluetooth_gap_advertise_stop'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_advertise+0x8): undefined reference to `mp_bluetooth_gap_advertise_start'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x20): undefined reference to `mp_bluetooth_gap_get_device_name'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x24): undefined reference to `mp_bluetooth_get_current_address'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x28): undefined reference to `mp_bluetooth_get_preferred_mtu'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x2c): undefined reference to `mp_bluetooth_gap_set_device_name'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x30): undefined reference to `mp_bluetooth_set_preferred_mtu'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x34): undefined reference to `mp_bluetooth_set_address_mode'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x38): undefined reference to `mp_bluetooth_set_bonding'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x3c): undefined reference to `mp_bluetooth_set_mitm_protection'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x40): undefined reference to `mp_bluetooth_set_io_capability'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_config+0x44): undefined reference to `mp_bluetooth_set_le_secure'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_active+0x0): undefined reference to `mp_bluetooth_init'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_active+0x4): undefined reference to `mp_bluetooth_deinit'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_active+0x8): undefined reference to `mp_bluetooth_is_active'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_connect+0x4): undefined reference to `mp_bluetooth_gap_peripheral_connect_cancel'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj):(.literal.bluetooth_ble_gap_connect+0x8): undefined reference to `mp_bluetooth_gap_peripheral_connect'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gattc_exchange_mtu':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:145:(.text.bluetooth_ble_gattc_exchange_mtu+0xc): undefined reference to `mp_bluetooth_gattc_exchange_mtu'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gattc_write':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:847:(.text.bluetooth_ble_gattc_write+0x3c): undefined reference to `mp_bluetooth_gattc_write'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gattc_read':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:832:(.text.bluetooth_ble_gattc_read+0x15): undefined reference to `mp_bluetooth_gattc_read'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gattc_discover_descriptors':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:824:(.text.bluetooth_ble_gattc_discover_descriptors+0x21): undefined reference to `mp_bluetooth_gattc_discover_descriptors'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gattc_discover_characteristics':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:816:(.text.bluetooth_ble_gattc_discover_characteristics+0x42): undefined reference to `mp_bluetooth_gattc_discover_characteristics'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gattc_discover_services':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:801:(.text.bluetooth_ble_gattc_discover_services+0x2c): undefined reference to `mp_bluetooth_gattc_discover_primary_services'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gatts_set_buffer':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:781:(.text.bluetooth_ble_gatts_set_buffer+0x26): undefined reference to `mp_bluetooth_gatts_set_buffer'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gatts_notify_indicate':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:763:(.text.bluetooth_ble_gatts_notify_indicate+0x37): undefined reference to `mp_bluetooth_gatts_notify_indicate'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gatts_write':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:748:(.text.bluetooth_ble_gatts_write+0x2e): undefined reference to `mp_bluetooth_gatts_write'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gatts_read':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:736:(.text.bluetooth_ble_gatts_read+0x13): undefined reference to `mp_bluetooth_gatts_read'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gatts_register_services':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:590:(.text.bluetooth_ble_gatts_register_services+0x47): undefined reference to `mp_bluetooth_gatts_register_service_begin'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_gatts_register_service':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:567:(.text.bluetooth_ble_gatts_register_services+0x272): undefined reference to `mp_bluetooth_gatts_register_service'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:567:(.text.bluetooth_ble_gatts_register_services+0x291): undefined reference to `mp_bluetooth_gatts_register_service_end'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gap_passkey':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:622:(.text.bluetooth_ble_gap_passkey+0x21): undefined reference to `mp_bluetooth_gap_passkey'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gap_pair':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:621:(.text.bluetooth_ble_gap_pair+0xc): undefined reference to `mp_bluetooth_gap_pair'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gap_disconnect':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:630:(.text.bluetooth_ble_gap_disconnect+0xc): undefined reference to `mp_bluetooth_gap_disconnect'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gap_scan':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:679:(.text.bluetooth_ble_gap_scan+0xb): undefined reference to `mp_bluetooth_gap_scan_stop'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:673:(.text.bluetooth_ble_gap_scan+0x70): undefined reference to `mp_bluetooth_gap_scan_start'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gap_advertise':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:463:(.text.bluetooth_ble_gap_advertise+0x1b): undefined reference to `mp_bluetooth_gap_advertise_stop'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `mp_get_buffer_raise':
/home/logik/lvgl_micropython/lib/micropython/py/obj.h:606:(.text.bluetooth_ble_gap_advertise+0x71): undefined reference to `mp_bluetooth_gap_advertise_start'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_config':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:312:(.text.bluetooth_ble_config+0x2f): undefined reference to `mp_bluetooth_gap_get_device_name'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:316:(.text.bluetooth_ble_config+0x47): undefined reference to `mp_bluetooth_get_current_address'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:322:(.text.bluetooth_ble_config+0x71): undefined reference to `mp_bluetooth_get_preferred_mtu'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:345:(.text.bluetooth_ble_config+0xfa): undefined reference to `mp_bluetooth_gap_set_device_name'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:349:(.text.bluetooth_ble_config+0x10d): undefined reference to `mp_bluetooth_set_preferred_mtu'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:390:(.text.bluetooth_ble_config+0x124): undefined reference to `mp_bluetooth_set_address_mode'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_handle_errno':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:89:(.text.bluetooth_ble_config+0x135): undefined reference to `mp_bluetooth_set_bonding'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_config':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:395:(.text.bluetooth_ble_config+0x145): undefined reference to `mp_bluetooth_set_mitm_protection'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:401:(.text.bluetooth_ble_config+0x158): undefined reference to `mp_bluetooth_set_io_capability'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:406:(.text.bluetooth_ble_config+0x16c): undefined reference to `mp_bluetooth_set_le_secure'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_active':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:416:(.text.bluetooth_ble_active+0xf): undefined reference to `mp_bluetooth_init'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_handle_errno':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:342:(.text.bluetooth_ble_active+0x1a): undefined reference to `mp_bluetooth_deinit'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_active':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:428:(.text.bluetooth_ble_active+0x20): undefined reference to `mp_bluetooth_is_active'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main_esp32/libmain_esp32.a(modbluetooth.c.obj): in function `bluetooth_ble_gap_connect':
/home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:641:(.text.bluetooth_ble_gap_connect+0xb): undefined reference to `mp_bluetooth_gap_peripheral_connect_cancel'
/home/logik/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/logik/lvgl_micropython/lib/micropython/extmod/modbluetooth.c:654:(.text.bluetooth_ble_gap_connect+0x9c): undefined reference to `mp_bluetooth_gap_peripheral_connect'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

</details>

with more that 375 pull request and 1.5k issues, I don't know if micropython will be as reactive as you....

**Comment by kdschlosser** [comment]
yes I will have this fixed in the next 8 to 10 hours

**Comment by kdschlosser** [comment]
This should be fixed.
