### ISSUE TITLE
RGB -> BGR on ili9341

### ISSUE THREAD

**Issue by zelogik** [kdschlosser/lvgl_micropython#55]
Hi,

I have read than putting:
color_byte_order=BYTE_ORDER_BGR, in the contructor of the display should work 2 weeks ago (in another issue on this repo)

But have you done some work there too ? because with or without putting that, the Red is displayed Blue, and blue is red. I can have a look at it if you say that you have touched something on that driver :D

**Comment by kdschlosser** [comment]
you need to set `rgb565_byte_swap` to `True`

**Comment by zelogik** [comment]
With a constructor like that:
`
display = ili9341.ILI9341(
...
    color_space=lv.COLOR_FORMAT.RGB565,
    color_byte_order=ili9341.BYTE_ORDER_BGR,
    rgb565_byte_swap=True
)
`
Tested with rgb565_byte_swap  True|False, color_byte_order commented|RBG|BGR

exactly the same wrong color order ...

**Comment by kdschlosser** [comment]
I am going to have to make a change to the code, give me a little while to do that.

**Comment by kdschlosser** [comment]
OK I made the changes needed to the driver IC. so this should be all set.
