### ISSUE TITLE
Unix Port error on sdl_display.py init

### ISSUE THREAD

**Issue by getznerh** [kdschlosser/lvgl_micropython#60]
I have compiled the latest unix port without any error.
With the test example from readme i got an error

File "sdl_display.py", line 157, in __init__
TypeError: function missing 2 required positional arguments

in the example we have:
`display = sdl_display.SDLDisplay(
    data_bus=bus,
    display_width=_WIDTH,
    display_height=_HEIGHT,
    frame_buffer1=buf1,
    frame_buffer2=buf2,
    color_space=lv.COLOR_FORMAT.RGB888
)
`
what are the right parameters for the constructor?

**Comment by kdschlosser** [comment]
This is now fixed. sorry about that I had forgotten to update the sdl display driver.
